# -*- coding: utf-8 -*-
"""LLM clients and prompt templates."""

from common.ais.prompts import (
    OUTPUT_LANGUAGE,
    LANGUAGE_POLICY,
    CLARIFY_SYSTEM_PROMPT,
    OUTPUT_FORMATTER_SYSTEM_PROMPT,
    INSTAGRAM_REELS_SCRIPT_SYSTEM_PROMPT,
    INSTAGRAM_REELS_CAPTION_SYSTEM_PROMPT,
    YOUTUBE_SHORTS_SCRIPT_SYSTEM_PROMPT,
    YOUTUBE_SHORTS_CAPTION_SYSTEM_PROMPT,
    TIKTOK_SCRIPT_SYSTEM_PROMPT,
    TIKTOK_CAPTION_SYSTEM_PROMPT,
    FACEBOOK_SCRIPT_SYSTEM_PROMPT,
    FACEBOOK_CAPTION_SYSTEM_PROMPT,
    SHORT_FORM_BUNDLE_SYSTEM_PROMPT,
    get_short_form_system_prompt,
    build_content_user_prompt,
)

__all__ = [
    "OUTPUT_LANGUAGE",
    "LANGUAGE_POLICY",
    "CLARIFY_SYSTEM_PROMPT",
    "OUTPUT_FORMATTER_SYSTEM_PROMPT",
    "INSTAGRAM_REELS_SCRIPT_SYSTEM_PROMPT",
    "INSTAGRAM_REELS_CAPTION_SYSTEM_PROMPT",
    "YOUTUBE_SHORTS_SCRIPT_SYSTEM_PROMPT",
    "YOUTUBE_SHORTS_CAPTION_SYSTEM_PROMPT",
    "TIKTOK_SCRIPT_SYSTEM_PROMPT",
    "TIKTOK_CAPTION_SYSTEM_PROMPT",
    "FACEBOOK_SCRIPT_SYSTEM_PROMPT",
    "FACEBOOK_CAPTION_SYSTEM_PROMPT",
    "SHORT_FORM_BUNDLE_SYSTEM_PROMPT",
    "get_short_form_system_prompt",
    "build_content_user_prompt",
]
